apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
      annotations:
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8099"
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: config-server
          image: normat/config-server:latest
          ports:
            - containerPort: 8099
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  labels:
    app: config-server
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8099"
    prometheus.io/scrape: "true"
spec:
  selector:
    app: config-server
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http-traffic
      port: 8099
      targetPort: 8099
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: config-server-monitor
  labels:
    app: config-server
    release: prometheus
spec:
  selector:
    matchLabels:
      app: config-server
  endpoints:
    - port: http-traffic
      path: "/actuator/prometheus"
      interval: 30s  # Specify the scrape interval
      scrapeTimeout: 10s  # Specify the scrape timeout
