apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8099"
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: normat/config-server:latest
          ports:
            - containerPort: 8099
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  type: NodePort
  ports:
    - port: 8099
      nodePort: 30099
  selector:
    app: config-server