apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpb-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpb-postgres
  template:
    metadata:
      labels:
        app: gpb-postgres
    spec:
      containers:
        - name: gpb-postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_DB
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
---
apiVersion: v1
kind: Service
metadata:
  name: gpb-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: gpb-postgres
---