apiVersion: apps/v1
kind: Deployment
metadata:
  name: middle-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: middle-service
  template:
    metadata:
      labels:
        app: middle-service
    spec:
      containers:
        - name: middle-service
          image: normat/middle-service:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: spring.datasource.url
              value: jdbc:postgresql://gpb-postgres:5432/gpb
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
            - name: spring.flyway.user
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: spring.flyway.password
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
            - name: spring.flyway.url
              value: jdbc:postgresql://gpb-postgres:5432/gpb
            - name: spring.flyway.locations
              value: classpath:db/migration
            - name: spring.flyway.enabled
              value: "true"
            - name: backend.base-url
              value: http://fake-backend:8080
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: middle-service
spec:
  type: NodePort
  ports:
    - port: 8082
      nodePort: 30002
  selector:
    app: middle-service
