apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-bot
  template:
    metadata:
      labels:
        app: telegram-bot
      annotations:
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8081"
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: telegram-bot
          image: normat/telegram-bot:latest
          env:
            - name: TELEGRAM_GPB_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: telegram-bot-secrets
                  key: TELEGRAM_GPB_BOT_TOKEN
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: telegram-bot-service
  labels:
    app: telegram-bot
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8081"
    prometheus.io/scrape: "true"
spec:
  selector:
    app: telegram-bot
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http-traffic
      port: 8081
      targetPort: 8081
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: telegram-bot-service-monitor
spec:
  selector:
    matchLabels:
      app: telegram-bot
  endpoints:
    - port: http-traffic
      path: "/actuator/prometheus"
