apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: config-server-monitor
  labels:
    app: config-server
spec:
  selector:
    matchLabels:
      app: config-server
  endpoints:
    - port: "8099"
      path: "/actuator/prometheus"