apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fake-backend-monitor
  labels:
    app: fake-backend
spec:
  selector:
    matchLabels:
      app: fake-backend
  endpoints:
    - port: "8099"
      path: "/actuator/prometheus"