apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: middle-service-monitor
  labels:
    app: middle-service
spec:
  selector:
    matchLabels:
      app: middle-service
  endpoints:
    - port: "8082"
      path: "/actuator/prometheus"